version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend
  order:
    build: ./order
    restart: always
    hostname: order
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  payment:
    build: ./payment
    restart: always
    hostname: payment
    env_file:
      - .env
    networks:
      - backend
    links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
      MYSQL_USER : ${DB_USERNAME}
      MYSQL_PASSWORD : ${DB_PASSWORD}
      MYSQL_DATABASE : ${DB_USERNAME}
      ports: 
        - 3306:3306
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    ports:
      - 27017:27017
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: app
